### ISSUE TITLE
Preview jumps a lot.

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor-vscode#169]
Hello!

According [issue 6](https://github.com/asciidoctor/asciidoctor-vscode/issues/6), problem is solved. But preview still jumps a lot when I typing smth.

[preview_pos_jumps (video).zip](https://github.com/asciidoctor/asciidoctor-vscode/files/2948217/preview_pos_jumps.video.zip).

Extension version is 2.3.3,
my settings:
```
"asciidoc.preview.scrollEditorWithPreview": false,
"asciidoc.preview.scrollPreviewWithEditor": false,
"asciidoc.preview.useEditorStyle": false,
```

Andrey.

**Comment by MatteoCampinoti94** [comment]
First thing: next time you post a video try making a gif so you can upload it directly without having to use zip files. Alternatively you can host it somewhere.

As for the jumping, I don't see anything like that on my machine. It might have something to do with using Cyrillic script inside a table.

Could you post part of your table so I can test it myself?

**Comment by sindzicat** [comment]
Interesting... Your gif is about 1.4 MB. I used [Captura](https://github.com/MathewSachin/Captura) to create my gif and got about 100MB. This is why I preferred to made mp4 video in the archive. How did you create your gif? Really interesting!

Also I found I can't read any text on gif. My video didn't have this problem. Maybe this is the main reason your gif is much smaller than 100MB.

> Could you post part of your table so I can test it myself?

There is no secret or personal info in this file. So I can show full file:

```
= Дифференциальные уравнения
:nofooter:
:stem: latexmath
:c: 0
:lq: &laquo;
:rq: &raquo;

++++
<style>
    body {
        background-color: white;
        color: rgba(0,0,0,0.8);
        font-family:"Times New Roman";
        font-size: 18px;
    }
</style>
++++

[cols="^1,7a,7a",width=100%]
|===
^h| №
^h| Вопрос
^h| Ответ

| {counter:c}
| Дифференциальное уравнение.
| Дифференциальным уравнением называется уравнение, связывающее независимую переменную stem:[x], искомую функцию stem:[y = f(x)] и её производные stem:[y', y'', \ldots, y^{(n)}].

| {counter:c}
| Цепные линии.
| Графики всевозможных функций, которые соответствуют решению дифференциального уравнения.

| {counter:c}
| Порядок дифференциального уравнения.
| Порядок наивысшей производной, входящей в уравнение.

// | {counter:c}
// | Решение дифференциального уравнения.
// | Всякая функция stem:[y = f(x)], которая, будучи подставлена в уравнение, превращает его в тождество.

| {counter:c}
| Интеграл дифференциального уравнения.
| См. {lq}решение дифференциального уравнения{rq}.

| {counter:c}
| Начальное условие.
| Условие, что при stem:[x = x_0] функция stem:[y] дожна равняться заданному числу stem:[y_0].

| {counter:c}
| Общее решение дифференциального уравнения первого порядка.
| Функция stem:[y = \varphi(x, C)], которая зависит от одной произвольной постоянной stem:[C] и удовлетворяет следующим условиям:

* удовлетворяет дифференциальному уравнению при любом конкретном значении постоянной stem:[C];
* каково бы ни было начальное условие stem:[y = y_0] при stem:[x = x_0], т.е. stem:[\left . y \right \vert_{x = x_0} = y_0 ], можно найти такое значение stem:[C = C_0], что функция stem:[y = \varphi(x, C_0)] удовлетворяет данному начальному условию^1^.

^1^При этом предполагается, что значения stem:[x_0] и stem:[y_0] принадлежат к той области изменения переменных stem:[x] и stem:[y], в которой выполняются условия теоремы существования и единственности функции.

| {counter:c}
| Общий интеграл дифференциального уравнения.
| Равенство вида stem:[\Phi(x, y, C) = 0], неявно задающее общее решение.

| {counter:c}
| Частное решение дифференциального уравнения.
| Любая функция stem:[y = \varphi(x, C_0)], которая получается из общего решения stem:[y = \varphi(x, C)], если в последнем произвольной постоянной придать определённое значение stem:[C = C_0].

| {counter:c}
| Частный интеграл уравнения.
| Соотношение вида stem:[\Phi(x, y, C_0)].

| {counter:c}
| Общий интеграл с геометрической точки зрения.
| С геометрической точки зрения общий интеграл представляет собой семейство кривых на координатной плоскости, зависящее от одной произвольной постоянной stem:[C].

| {counter:c}
| Интегральные кривые дифференциального уравнения.
| Это кривые (графики функций), соответствующие общему интегралу дифференциального уравнения.

| {counter:c}
| Решить дифференциальное уравнение.
| Решить дифференциальное уравнение -- значит:

* найти его общее решение или общий интеграл, если начальные условия не заданы;
* найти то частное решение уравнения, которое удовлетворяет заданным начальным условиям (если таковые имеются).

| {counter:c}
| Проинтегрировать дифференциальное уравнение.
| См. {lq}Решить дифференциальное уравнение{rq}.

| {counter:c}
| Дифференциальное уравение с геометрической точки зрения.
| С геометрической точки зрения дифференциальное уравнение stem:[\cfrac{d y}{d x} = f(x, y)] определяет _поле направлений_ на координатной плоскости stem:[Oxy].

| {counter:c}
| Задача решения/интегрирования дифференциального уравнения с геометрической точки зрения.
| С геометрической точки зрения задача решения (интегрирования) дифференциального уравнения заключается в нахождении кривых, направление касательных к которым совпадает с направлением поля в соответствующих точках.

| {counter:c}
| Изоклина дифференциального уравнения.
| Геометрическое место точек, в которых выполняется соотношение stem:[\cfrac{d y}{d x} = \text{const}].

| {counter:c}
| Установить связь между stem:[x], stem:[y] и stem:[\cfrac{d y}{d x}].
| Имеем stem:[y = \varphi(x, C)]. (1)

. Дифференциируем (1) по stem:[x]: stem:[\cfrac{d y}{d x} = \varphi'_x(x, C)] (2).
. Выводим из (1) stem:[C] и подставляем его в (2).

| {counter:c}
| Уравнение с разделёнными переменными.
| Дифференциальное уравнение вида
[stem]
++++
M(x)dx + N(y)dy=0,
++++

где stem:[M(x)] -- функция, зависящая от stem:[x], +
stem:[N(y)] -- функция, зависящая от stem:[y].

| {counter:c}
| Общий интеграл дифференциального уравнения с разделёнными переменными.
| [stem]
++++
\int M(x) d x + \int N(y) dy = C
++++


| {counter:c}
| Уравнение с разделяющимися переменными.
| Уравнение вида
[stem]
++++
M_1(x) N_1(y) dx + M_2(x) N_2(y)dy = 0
++++

или 

[stem]
++++
\cfrac{ M_1(x) }{ M_2(x) } dx + \cfrac{ N_1(y) }{ N_2(y) } dy = 0
++++

| {counter:c}
| Однородная функция stem:[n]-го измерения.
| Функция stem:[f(x,y)] называется однородной функцией stem:[n]-го измерения относительно переменных stem:[x] и stem:[y], если при любом stem:[\lambda] справедливо тождество:
[stem]
++++
f(\lambda x, \lambda y) = \lambda^n f(x,y)
++++

| {counter:c}
| Как определить, является ли функция однородной и какая у неё степень измерения.
| [stem]
++++
f(x, y) = \sqrt[3]{x^3 + y^3}, \\
f(\lambda x, \lambda y) = \sqrt[3]{(\lambda x)^3 + (\lambda y)^3} = \lambda \sqrt[3]{x^3 + y^3}.
++++

Функция stem:[f(x, y) = \sqrt[3\]{x^3 + y^3}] является однородной функцией 1-го измерения.

| {counter:c}
| Однородное уравнение первого порядка.
| Уравнение первого порядка 
[stem]
++++
\cfrac{dy}{dx} = f(x,y)
++++
называется __однородным__ относительно stem:[x] и stem:[y], если функция stem:[f(x,y)] есть однородная функция __нулевого измерения__ относительно stem:[x] и stem:[y].

| {counter:c}
| Решение однородного уравнения
| TODO: стр. 26

| {counter:c}
| Условие однородности уравнения вида stem:[M(x,y)dx + N(x,y)dx = 0].
| Уравнение вида stem:[M(x,y)dx + N(x,y)dx = 0] будет однородным в том и только в том случае, когда stem:[M(x,y)] и stem:[N(x,y)] являются однородными функциями одного и того же измерения^1^.

^1^Это вытекает из того, что отношение двух однородных функций одного и того же измерения является однородной функцией нулевого измерения.

| {counter:c}
| Почему уравнение вида
[stem]
++++
\cfrac{ dy }{ dx } = \cfrac{ ax + by + c }{ a_1 x + b_1 y + c_1 }
++++
приводится к однородному?
| см. стр. 28

| {counter:c}
| Линейное уравнение первого порядка.
| Линейным уравнением первого порядка называется уравнение вида stem:[\cfrac{ dy }{ dx } + P(x)y = Q(x)], линейное относительно неизвестной функции и её производной.

|===
```

**Comment by MatteoCampinoti94** [comment]
For the GIF: you can use `ffmpeg` on a Linux machine or an online tool on any device ^^

Thanks for the file, I'll check if it gives me the same problem.

**Comment by MatteoCampinoti94** [comment]
No problems here. I've tried typing a bit and even copy pasting new Cyrillic characters, but the preview kept working fine.

**Comment by MatteoCampinoti94** [comment]
It might be a problem with Windows, but I can test it as I don't have a Win machine where I am.

Try removing your asciidoc settings, except for `useEditorStyle`, leave that to `false`.

**Comment by sindzicat** [comment]
At this case, chrome devtools should help us. I found there is some problems with Asciidoctor while I type smth.
```
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:1398   ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at MarkdownFoldingProvider.<anonymous> (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Sindzicat\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] GOT MESSAGE
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
workbench.main.js:sourcemap:3627 [Embedded Page] Uncaught TypeError: Cannot read property 'element' of undefined
```

**Comment by MatteoCampinoti94** [comment]
Please don't post such long messages, use a text file ^^

We are aware of the folding provider error, it's not related to the preview.

**Comment by sindzicat** [comment]
> Please don't post such long messages, use a text file 

Done.

**Comment by sindzicat** [comment]
@MatteoCampinoti94, how can I help you to find the root of this problem?
I can get you remote access via Teamviewer.
You can write me on my email (it's in my profile).

**Comment by MatteoCampinoti94** [comment]
Sorry, busy week x.x
No don't worry, don't need access ^^

Try to uninstall VSCode, clear all its settings, extensions, workspaces settings, etc... then reinstall it and your extensions. Then open your file and start editing, use the default VSCode settings and only install our extension to test it. If the preview still jumps after all that then it's most likely something related to your machine.

**Comment by sindzicat** [comment]
I downloaded zip archive of VS Code, made it really portable using [these instructions](https://code.visualstudio.com/docs/editor/portable). Preview jumps...

**Comment by danyill** [comment]
@sindzicat thanks for filing this issue. Thanks especially for providing a document with an example. I've tried your document on the latest version of vs code and can confirm that this is still an issue.

I've done a little research...

1. I think MathJax (which is used for the formula rendering) is triggering re-rendering of the page layout using JavaScript (the movement doesn't occur if I comment out `:stem: latexmath`).

2. This extension current assigns a source file line number against all blocks, but is unable to assign them against individual table rows (or cells) because the upstream support is absent for (easily) adding this information.

3. If upstream implements https://github.com/asciidoctor/asciidoctor/issues/1338 I believe this may improve things because then each cell would be a block and would naturally get a line number provided to it with the converters support. Then (I think) the jumping would only go to the nearest line number.

4. Another option is to change when we get the rendering information so we go back to the "correct" point. I'm not exactly sure but I think we are taking information from `getBoundingClientRect` _during_ the MathJax rendering phase which gives us the result we see (we get the height as higher/closer to the top than it really is because MathJax has not finished the layout). Over several renders this presents as a "scrolling up the preview" which you've observed.

5. How to fix? Well we could wait longer for the preview to finish (but this might make the extension laggy) or we could (most likely should) register in event or watch for a completed action in the MathJax event output (see [here](https://github.com/mathjax/mathjax-docs/wiki/Event-when-typesetting-is-done%3F-Rescaling-after-rendering...))

6. At present however our preview code has a problem with the sourcemap so I'm struggling to debug it correctly and need to resolve that first.

**Comment by sindzicat** [comment]
Maybe, just create setting for autoupdate on <kbd>CTRL</kbd>+<kbd>S</kbd> for such case?
Also, what version of Mathjax is used? Version 3 is much more faster.

**Comment by danyill** [comment]
@sindzicat currently we use MathJax 2.7.5 which is what the Asciidoctor project provides. There is an [issue](https://github.com/asciidoctor/asciidoctor/issues/3449) with an associated PR for upgrading to MathJax 3 but it is not a drop in replacement so will likely need a major version bump in Asciidoctor.

Thanks for the document link -- let's leave this issue open for further testing/work if the upstream situation changes.

The idea of having a configuration option for updating preview only on save is a good one and has been suggested previously. I'll look into this at some stage.

**Comment by danyill** [comment]
Eek. Forget the bit about the document link! Wrong issue.

**Comment by prudhomm** [comment]
I confirm the issue with math. I am using vscode with the extension and i have to disable math preview. I
The edition page moves vertically when i type and it becomes unusable.
I was using vscode +asciidoc to discusd online with students and show them the math as I type. Unfortunately that is not possible due to this issue

**Comment by prudhomm** [comment]
actually it is not only with tables but whenever there is math.

Here is an example, if you try adding math while previewing you will get a lot of jumps and it gets very hard to actually edit.
```adoc
=== Norme stem:[L^2]

[.left.x-small]
--
[stem.small]
++++
\| u_h = \sum u_i   \phi_i \|_2^2 =\int_\Omega u_h*u_h \approx \\
\sum_K \sum_{q=1}^Q  w_q u_h \circ T_K (\hat{x}_q)*u_h \circ T_K (\hat{x}_q) |det \nabla T_K | \\
u_h\circ T_K (\hat{x}_q)= \sum_{i=1}^3 u_{connect(K,i)} \phi_i(\hat{x_q})
++++

IMPORTANT: choisir une formule de quadrature d'ordre stem:[2k] pour stem:[u_h \in P^k_{c,h}]
--

=== Norme stem:[L^2] (suite)

[.left.x-small]
--
Pour stem:[u] on a:

[stem.small]
++++
\|u  \|_2^2 =\int_\Omega u*u \approx,\quad 
\sum_K \sum_{q=1}^Q  w_q u \circ T_K (\hat{x}_q)*u \circ T_K (\hat{x}_q) |det \nabla T_K | \\
++++

NOTE: il faut calculer stem:[x_{K,q}=T_K(\hat{x}_q)], puis calculer stem:[u(x_{K,q})].
--

=== SemiNorme stem:[H^1]

[stem.x-small]
++++
\|\nabla u_h = \sum u_i \nabla \phi_i \|^2_2 =\int_\Omega \nabla u_h \cdot \nabla u_h = \\
\sum_K \int_\hat{K} \nabla u_h \circ T_K \cdot \nabla u_h \circ T_K |det \nabla T_K | = \\
\sum_K \int_\hat{K} \hat{\nabla} u_h \nabla T_K^{-1} \cdot \hat{\nabla} u_h \nabla T_K^{-1} |det \nabla T_K | \approx \\
\sum_K \sum_{q=1}^Q  w_q \hat{\nabla} u_h \nabla T_K^{-1} * \hat{\nabla} u_h \nabla T_K^{-1} |det \nabla T_K | \\
\hat{\nabla} u_h = \sum_{i=1}^3 u_{connect(K,i)} \hat{\nabla} \phi_i,\quad
\nabla u_{h_|K} = \sum_{i=1}^3 u_{connect(K,i)} \hat{\nabla} \phi_i \nabla T_K^{-1}
++++

===  SemiNorme stem:[H^1] (suite)

[.left.x-small]
--
Si stem:[u] quelconque, soit on calcule l'interpolant de stem:[u], stem:[\pi^1_h u], dans stem:[P^1_{c,h}] puis la semi norme stem:[H^1] en utilisant l'interpolant, soit on  connait le gradient de stem:[u] et on utilise celui ci dans les formules de quadratures

[stem.x-small]
++++
\pi^1_h u (x_j) = \sum_{i=1}^N u(x_j) \psi_i(x_j) = u(x_j) * \delta_{i,j} = u(x_j)\\
++++
stem:[\pi^1_h u ] est l'élément de stem:[P^1_{c,h}] dont les composantes sont stem:[(u(x_1),\ldots,u(x_N)))^T].

[source,python]
--
 # nodes renvoit une paire (i,(x,y))
for N in nodes:
    Piu[N.i] = fonction_u(N.x,N.y)
--
--


=== Assemblage des matrices de raideur

[.left.x-small]
--
stem:[A] avec condition de dirichlet.

on assemble stem:[A] *_sans condition Dirichlet._*

[stem.x-small]
++++
\|\nabla u_h \|^2 = U_h^T A U_h = \int_\Omega \nabla u_h  \cdot \nabla u_h\\
u_h = \sum_{i=1} U_i \psi_i(x)
++++
avec stem:[U_h] le vecteur des composantes de stem:[u_h] dans la base de Lagrange stem:[P^1].
--

=== Assemblage des matrices de raideur (suite)

Pour stem:[u] on a

[stem.x-small]
++++
\|\nabla u \|^2 \approx \|\nabla \pi^1_h u \|^2 = \Pi_h^T A \Pi_h = \int_\Omega \nabla \pi^1_h u  \cdot \nabla \pi^1_h u,\quad \mbox{ avec } \pi^1_h u = \sum_{i=1} u(x_i) \psi_i(x)
++++
avec stem:[\Pi_h] le vecteur des composantes de stem:[\pi^1_h u] dans la base de Lagrange stem:[P^1].
```

**Comment by sindzicat** [comment]
@prudhomm, I switched to [Asciidoctor Chrome extension](https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia). I updates content only when I save it in vscode. You can set up autosave file in vscode and so you will get autoupdate in Chrome. And this will work much more comfortable then preview from vscode extension.

**Comment by ggrossetie** [comment]
It has been fixed in the next major version:

https://github.com/user-attachments/assets/8548f863-382c-4a6a-816e-58ebd85043e3
