### ISSUE TITLE
Convert to PDF does not render images from included adoc files

### ISSUE THREAD

**Issue by GitHubNull** [asciidoctor/asciidoctor-vscode#186]
when incude sub asciidoc file, and then cover to pdf it can not render sub asciidoc file images at all!

**Comment by MatteoCampinoti94** [comment]
I've tested with nested directories and nested inclusions, images render without problems. What does it show exactly in your pdf? If it shows something like `[path/to/image]` then the processor could not find an image at the specified link (if it shows something else or you're already well versed in asciidoc grammar ignore the next comment, it's a standard one I use for issues like this just in case).

**Comment by MatteoCampinoti94** [comment]
If you specified the `imagesdir` attribute in the top file (the spine) then that attribute will be inherited by all the lower sections (unless you specify `imagesdir` in a lower header).

If you did not specify the `imagesdir` attribute anywhere then all image blocks links will be relative to the document they are used in.

```
Spine.adoc
|--- chapter1/
|      |--- chapter 1a.adoc
|      +--- chapter 1b.adoc
|--- chapter2.adoc
+--- image_c1a.png
```

If you use something like `image:image_c1a.png[]` in `chapter1a.adoc` then the processor will look for `image_c1a.png` under folder `chapter1/` but won't find it. So you can either use a relative link (`../image_c1a.png`) or declare the `imagesdir` attribute in the `Spine.adoc` header. In this specific example you'd declare it as `:imagesdir: .` so that every lower image block will look for the image file relative to the root of your project.

**Comment by MatteoCampinoti94** [comment]
I'll need you to provide us with your VSCode version, the version of the extension you have currently installed and a general layout of your project tree. If you want you can also include the project itself as a zip archive (provided it is small enough, please don't send anything bigger than 5MB).

**Comment by GitHubNull** [comment]
sorry about that, I solved it by myself, I found it was path problem. And I found it cound be solved by use the absolute path for imagesdir. And last, thank you very much!

**Comment by MatteoCampinoti94** [comment]
Glad it's solved ^.^

**Comment by igagis** [comment]
Faced the same problem. For some reason absolute `:imagesdir:` path is required which is not good. How to make it work with relative path?

**Comment by MrKalach** [comment]
The issue is still present. The relative path doesn't work, only with the absolute path in `:imagesdir:`.

Windows 10, VSCode 1.66.2, AsciiDoc plugin v2.9.8. Default settings.

**Comment by MrKalach** [comment]
A possible fix could be to run `wkhtmltopdf` from the root folder of the document location, for that you need to fix this [function](https://github.com/asciidoctor/asciidoctor-vscode/blob/5853aa96e14a2b6fc56ce9445999982e1ec8f79e/src/commands/exportAsPDF.ts#L253)

I don't know TypeScript and I don't have dev environment set up for it, so I can't do a PR and test changes. Maybe somebody else could try to implement and make a PR?

**Comment by Mogztter** [comment]
That's already the case, we are using `cwd` with the `documentPath`: https://github.com/asciidoctor/asciidoctor-vscode/blob/5853aa96e14a2b6fc56ce9445999982e1ec8f79e/src/commands/exportAsPDF.ts#L271

> cwd [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [<URL>](https://nodejs.org/api/url.html#the-whatwg-url-api) Current working directory of the child process.

https://nodejs.org/api/child_process.html#child_processspawncommand-args-options


> could you re-open this ticket?

@MrKalach Please open a new ticket with a minimal reproduction case. I'm not 100% sure that the original issue was related to `wkhtmltopdf` (since we support both `asciidoctor-pdf` and `wkhtmltopdf`).

**Comment by MrKalach** [comment]
@Mogztter done, ticket #568
